### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yuler** [yuler/learn-electron#4]
- [x] https://github.com/sindresorhus/electron-store
- [ ] https://github.com/sindresorhus/electron-dl
- [x] https://github.com/sindresorhus/electron-util
- [ ] https://github.com/sindresorhus/electron-better-ipc
